[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "jsonschema>=4.25.1",
    "openai>=1.102.0",
    "plotly>=6.3.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.49.1",
]
