[server]
headless = true
address = "0.0.0.0"
<<<<<<< HEAD
port = 5000
=======
port = 8501            # Render will override with $PORT
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
>>>>>>> 10ee80dfd54fc7fcb116471a8a91a0ae3f357be3
