[server]
headless = true
address = "0.0.0.0"
port = 8501            # Render will override with $PORT
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
